data-send-delay: 5
entity-view-distance: 50
join-send-delay: 20
entity-position-update-period: 35
model-entity-type: IRON_GOLEM # must be a living entity
enable-part-visibility-models:
  - example
debug: false